In [7]:
import numpy as np
#1:8*8棋盘矩阵，其中1、3、5、7行&&0、2、4、6列的元素置为1   1 ,3，5，7列&&0,2,4,6行也是1
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print z


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [6]:
#2：min()、max()函数

In [9]:
z = np.random.random((10,10))
zmin,zmax = z.min(),z.max()

In [12]:
#归一化，将矩阵规格化到0～1，即最小的变成0，最大的变成1，最小与最大之间的等比缩放
z = 10*np.random.random((5,5))
print z
zmin,zmax = z.min(),z.max()
z = (z-zmin)/(zmax-zmin)
print z

[[ 5.64509768  0.68146094  8.23694681  0.07100285  7.37379186]
 [ 0.0752762   9.7764589   7.80421002  6.11552908  2.6865688 ]
 [ 9.8869914   1.44285425  0.89132992  2.59310328  0.56864919]
 [ 6.55186281  8.26647432  6.15930931  4.22051594  7.03349304]
 [ 4.74498093  0.58582793  3.09918065  2.54389279  7.28846041]]
[[  5.67858734e-01   6.21901795e-02   8.31902351e-01   0.00000000e+00
    7.43968778e-01]
 [  4.35345679e-04   9.88739545e-01   7.87817461e-01   6.15783749e-01
    2.66459759e-01]
 [  1.00000000e+00   1.39756825e-01   8.35704993e-02   2.56937996e-01
    5.06975256e-02]
 [  6.60235078e-01   8.34910455e-01   6.20243842e-01   4.22730025e-01
    7.09300970e-01]
 [  4.76159692e-01   5.24476039e-02   3.08494430e-01   2.51924697e-01
    7.35275670e-01]]


In [14]:
#矩阵相加
z = np.zeros((5,5))
z += np.arange(5)
print np.arange(5)
print z


[0 1 2 3 4]
[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [16]:
#生成0~10之间均匀分布的11个数，包括0和10

z = np.linspace(0,10,11,endpoint=True,retstep=True)
print z


(array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]), 1.0)


In [18]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo